dist: xenial
install:
- lsb_release -a
- sudo apt-get update
- sudo apt-get install libglfw3-dev qt5-default -y --force-yes
- sudo apt-get install qt5-default qtscript5-dev -y --force-yes
- sudo apt-get install libassimp-dev cmake -y --force-yes
- sudo apt-get install libfreetype6 libfreetype6-dev libglm-dev libx11-dev libglm-dev -y --force-yes
- sudo apt-get install g++ -y --force-yes
- g++ --version
script:
- git clone --depth=50 --branch=master https://github.com/filipwasil/fillwave.git filipwasil/fillwave
- git submodule update --init --recursive
- git submodule update
- mkdir ../build
- cd ../build
- export COVERALLS_SERVICE_NAME=travis-ci
- export COVERALLS_REPO_TOKEN=d2o967X6pH4UAZo15vBcYHLH65BNRHIvN
- pip install --user cpp-coveralls
- cmake ../fillwave -DFILLWAVE_TESTS=OFF -DFILLWAVE_BUILD_LEVEL_EDITOR=OFF && make fillwave -j4
group: deprecated-2017Q2
